apiVersion: v1
kind: Service
metadata:
  name: gsa-gateway
  namespace: gsa
spec:
  type: ClusterIP
  selector:
    app: gsa-gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
